### ISSUE TITLE
Task Continuation

### ISSUE THREAD

**Issue by danielhorv** [tailoredmedia/Endpoints#19]
If you're using `withThrowingTaskGroup` for parallel execution and one of the calls fails, the Task is stuck, neither success nor failure.

The issue is also reproducible in a small example project:
[EndpointsExample.zip](https://github.com/diamirio/Endpoints/files/11721365/EndpointsExample.zip)

Console message: 
> SWIFT TASK CONTINUATION MISUSE: dataTask(for:) leaked its continuation!

**Comment by kaulex99** [comment]
This is going to be resolved in Endpoints 3.0.0
